# Generated by Django 4.2.3 on 2023-07-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChillSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('chilllsong', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='EnglishSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('englishsong', models.FileField(upload_to='')),
            ],
        ),
    ]
