# Generated by Django 4.2.3 on 2023-07-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0002_chillsong_englishsong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishsong',
            name='englishsong',
            field=models.CharField(max_length=250),
        ),
    ]
