# Generated by Django 4.2.3 on 2023-07-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0003_alter_englishsong_englishsong'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chillsong',
            old_name='chilllsong',
            new_name='chillsong',
        ),
    ]
