# Generated by Django 4.2.3 on 2023-07-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0004_rename_chilllsong_chillsong_chillsong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chillsong',
            name='chillsong',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='sadsong',
            name='sadsong',
            field=models.CharField(max_length=50),
        ),
    ]
