# Generated by Django 4.2.3 on 2023-07-13 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='emailId',
            new_name='username',
        ),
    ]
