# Generated by Django 4.2.3 on 2023-07-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_rename_emailid_users_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='emailId',
        ),
    ]
