# Generated by Django 4.2.3 on 2023-07-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_rename_emailid_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
