# Generated by Django 4.2.3 on 2023-07-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_alter_users_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='file',
            field=models.CharField(max_length=25000),
        ),
    ]
