# Generated by Django 4.2.3 on 2023-07-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FavoriteApp', '0002_rename_files_favorite_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='id',
        ),
        migrations.AddField(
            model_name='favorite',
            name='ref',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
