# Generated by Django 4.2.3 on 2023-07-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FavoriteApp', '0003_remove_favorite_id_favorite_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='file',
            field=models.CharField(max_length=10000000000000000000),
        ),
    ]
